# Approach taken from https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/.github/workflows/ci-ifcopenshell-conda-daily.yml
# Original work by Krande

name: ci

on: [push]

jobs:
  activate:
    runs-on: ubuntu-latest
    steps:
      - name: Set env
        run: echo ok go

  test:
    name: ${{ matrix.platform.distver }}-${{ matrix.pyver.name }}
    needs: activate
    runs-on: ${{ matrix.platform.distver }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        pyver: [
          { name: py312, distver: '3.12'}
        ]
        platform: [
          { name: Windows, distver: windows-2019 },
          { name: Linux, distver: ubuntu-20.04 },
          { name: macOS, distver: macos-13 }
        ]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Download MacOSX SDK
        if: ${{ matrix.platform.name == 'macOS' }}
        run: |
          curl -o MacOSX10.13.sdk.tar.xz -L https://github.com/phracker/MacOSX-SDKs/releases/download/11.3/MacOSX10.13.sdk.tar.xz && \
          tar xf MacOSX10.13.sdk.tar.xz && \
          sudo mv -v MacOSX10.13.sdk /opt/ && \
          ls /opt/
      - uses: mamba-org/setup-micromamba@v1 # https://github.com/mamba-org/setup-micromamba
        with:
          environment-name: build-env
          cache-environment: true
          condarc: |
            channels:
              - conda-forge
            channel_priority: strict
          create-args: >-
            python=3.11
            anaconda-client
            boa
      - name: build, test and upload ifcopenshell
        run: |
          conda mambabuild . --python ${{ matrix.pyver.distver }} -c conda-forge --token ${{ secrets.ANACONDA_TOKEN }} --user ifcopenshell
          
